[package]
name = "rust-hkid"
version = "0.1.0"
authors = ["Ilex Ng <ilex.ng@scmp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
